import { MinibufferView, MinibufferData } from "./minibuffer.slint";
import { EditorView, EditorData } from "./editor.slint";
import { ModeLineView, ModeLineData } from "./modeline.slint";

export component AppWindow inherits Window {
    width: 960px;
    height: 640px;
    title: window_title;

    in property <string> window_title: "altre";
    in property <MinibufferData> minibuffer;
    in property <EditorData> editor;
    in property <ModeLineData> modeline;

    callback key_event(KeyEvent);

    VerticalLayout {
        spacing: 0px;

        minibuffer_view := MinibufferView {
            width: parent.width;
            data: root.minibuffer;
        }

        editor_view := EditorView {
            width: parent.width;
            height: parent.height - minibuffer_view.height - mode_view.height;
            data: root.editor;
            key_event(event) => { root.key_event(event); }
        }

        mode_view := ModeLineView {
            width: parent.width;
            data: root.modeline;
        }
    }
}
