export enum MinibufferVisual {
    Inactive,
    Input,
    Info,
    Error,
}

export struct MinibufferData {
    style: MinibufferVisual,
    prompt: string,
    input: string,
    message: string,
    completions: [string],
}

export component MinibufferView inherits Rectangle {
    in property <MinibufferData> data;

    height: {
        if (root.data.completions.length > 0) {
            120px
        } else {
            36px
        }
    };
    background: {
        if (root.data.style == MinibufferVisual.Inactive || root.data.style == MinibufferVisual.Input) {
            #202020
        } else if (root.data.style == MinibufferVisual.Info) {
            #203020
        } else {
            #402020
        }
    };

    VerticalLayout {
        padding: 4px;
        spacing: 4px;

        HorizontalLayout {
            spacing: 6px;

            Text {
                text: root.data.prompt;
                font-family: "monospace";
                font-size: 13px;
                color: #9cdcfe;
            }

            Text {
                text: root.data.input;
                font-family: "monospace";
                font-size: 13px;
                color: #f8f8f2;
            }

            Text {
                text: root.data.message;
                font-family: "monospace";
                font-size: 13px;
                color: {
                    if (root.data.style == MinibufferVisual.Error) {
                        #ff6c6b
                    } else if (root.data.style == MinibufferVisual.Info) {
                        #a6e22e
                    } else {
                        #b0b0b0
                    }
                };
            }
        }

        for item[index] in root.data.completions: Text {
            text: item;
            font-family: "monospace";
            font-size: 12px;
            color: #a6e22e;
        }
    }
}
